export const GENRES = {
  action: "Hành động",
  adventure: "Phiêu lưu",
  animation: "Hoạt hình",
  comedy: "Hài hước",
  crime: "Tội phạm",
  documentary: "Tài liệu",
  drama: "Chính kịch",
  family: "Gia đình",
  history: "Lịch sử",
  horror: "Kinh dị",
  music: "Âm nhạc",
  mystery: "Huyền bí",
  fantasy: "Viễn tưởng - kỳ ảo",
  mentality: "Tâm lý",
  sport: "Thể thao",
  myth_supernatural: "Thần thoại - siêu nhiên",
  kids: "Thiếu nhi",
  romantic: "Lãng mạn",
  science_fiction: "Khoa học viễn tưởng",
  reality_show: "Truyền hình thực tế",
  thriller: "Kịch tính - giật gân",
};
